name: azulzulu-23-debian

on:
  push:
    branches:
    - main
    paths:
      - "azulzulu-23-debian/**"
      - .github/workflows/azulzulu-23-debian.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "azulzulu-23-debian/**"
      - .github/workflows/azulzulu-23-debian.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: azulzulu-23-debian
    secrets: inherit
